name: 02 - Workflow Events

on: 

  workflow_dispatch:
    inputs:
      input_value:
        description: "Please provide the input value"
        default: hello
        type: choice
        options:
          - akhil
          - harshika



jobs:
  echo:
    name: echo
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "Workflow is triggered by ${{github.event_name}} condition"
          echo "Workflow is triggered by ${{github.ref_name}} branch"


