name: 05 - 2 - Event Filters and Activity Types

on:
    workflow_dispatch:
jobs:
    echo:
        name: Echo
        runs-on: ubuntu-latest
        steps:
            - name: Echo step
              run: echo "unning whenever a PR is closed"

