name: 07 - Using Expressions
on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                default: false
                type: boolean

jobs:
    Echo:
        name: Echo
        runs-on: ubuntu-latest
        steps:
            - name:  Print start-up data
              if:  ${{ inputs.debug }} == 'true'
              run: |
                echo "Triggered by: ${{ github.event_name }}"
                echo "Branch: ${{ github.ref }}"
                echo "Commit SHA: ${{ github.sha }}"
                echo "Runner OS : ${{ Runner.OS }}"
                echo "Commit id: ${{ github.Commit }}"

            - name:  Print when triggered from main
              if:  ${{ inputs.debug }} == 'true' && ${{ github.ref_name }} == 'main'
              run: echo "I was triggered from main"

            - name: Hello World
              run: echo "Hello World"
