name: 07 - Using Expressions
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}
on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                default: false
                type: boolean



jobs:
    Echo:
        name: Echo
        runs-on: ubuntu-latest
        steps:
            - name:  Print start-up data
              if:  ${{ inputs.debug }}
              run: |
                echo "Triggered by: ${{ github.event_name }}"
                echo "Branch: ${{ github.ref }}"
                echo "Commit SHA: ${{ github.sha }}"
                echo "Runner OS : ${{ runner.os }}"
                echo "Commit id: ${{ github.commit }}"

            - name:  Print when triggered from main
              if:  ${{ inputs.debug   && github.ref_name == 'main' }} 
              run: echo "I was triggered from main"

            - name: Hello World
              run: echo "Hello World"
