name: 10 - Controlling the Execution Flow

run-name: 10 - Controlling the Execution Flow

on:
    workflow_dispatch:
        inputs:
            pass-unit-test:
                type: boolean
                default: false

jobs:
    lint-build:
        name: lint-build
        runs-on: ubuntu-latest
        steps:
            - name: Lint and build
              run: echo "Linting and building project" 
        
    unit-tests:
        name: unit-tests
        runs-on: ubuntu-latest
        #continue-on-error: true
        steps:
            - name: Running unit tests
              run: echo "Running tests..."
            
            - name: Failing tests
              if: ${{ !inputs.pass-unit-test}}
              run: exit 1

    
    deploy-nonprod:
        name: deploy-nonprod
        runs-on: ubuntu-latest
        needs: 
            - lint-build
            - unit-tests
        steps:
            - name: Deploying to nonprod
              run: echo "Deploying to nonprod..."
    
    e2e-tests:
        name: e2e-tests
        runs-on: ubuntu-latest
        needs:
            - deploy-nonprod
        steps:
            - name: Running E2E tests
              run: echo "Running E2E tests...."
    
    load-tests:
        name: load-tests
        runs-on: ubuntu-latest
        needs:
            - deploy-nonprod
        steps:
            - name: Running load tests
              run: echo "Running load tests...."

    deploy-prod:
        name: deploy-prod
        runs-on: ubuntu-latest
        needs: 
            - e2e-tests
            - load-tests
        steps:
            - name: Deploying to prod
              run: echo "Deploying to prod..."


