name: 12 - Working with Outputs

on:
    workflow_dispatch:
        inputs:
            build_status:
                description: Provide the build status
                type: choice
                options:
                    - success
                    - failure
                default: success

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.outputs.status }}
            output1: ${{ steps.build.outputs.output1 }}
        steps:
            - name: Print GITHUB _OUTPUT path
              run: |
                echo $GITHUB_OUTPUT
            
            - name: Build
              id: build
              run: |
                echo "status=${{ inputs.build_status }}" >> ${GITHUB_OUTPUT}
                echo "output1=value1" >> ${GITHUB_OUTPUT}
                echo "output2=value2" >> ${GITHUB_OUTPUT}
                cat ${GITHUB_OUTPUT}
                echo "mistake=true" > "$GITHUB_OUTPUT"
                cat ${GITHUB_OUTPUT}

    
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        needs: build
        if: ${{ needs.build.outputs.build-status == 'success' }}
        steps:
            - name: Deploy
              run: | 
                echo "Deploying"
                echo "${{needs.build.outputs.build-status}}"

            - name: Print outputs
              run: echo "${{ needs.build.outputs.output1 }}"

            